### ISSUE TITLE
Anime-Segmentation Node Crashing

### ISSUE THREAD

**Issue by marcussacana** [pythongosssss/ComfyUI-Custom-Scripts#1]
Hi, thanks for your scripts, this anime-segmentation one seems very usefull, but I'm geting this error, do you have a idea of why?

```txt
Traceback (most recent call last):
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\execution.py", line 174, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 3 more times]
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\execution.py", line 63, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\custom_nodes\anime_segmentation.py", line 59, in segment
    model = AnimeSegmentation.try_load(net, ckpt, device)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\ComfyUI\comfy_extras\anime_segmentation\train.py", line 72, in try_load
    model.load_state_dict(state_dict)
  File "C:\Users\Marcus\Documents\Ferramentas\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AnimeSegmentation:
        Unexpected key(s) in state_dict: "gt_encoder.conv_in.conv.weight", "gt_encoder.conv_in.conv.bias", "gt_encoder.conv_in.bn.weight", "gt_encoder.conv_in.bn.bias", "gt_encoder.conv_in.bn.running_mean", "gt_encoder.conv_in.bn.running_var", "gt_encoder.conv_in.bn.num_batches_tracked", "gt_encoder.stage1.rebnconvin.conv_s1.weight", "gt_encoder.stage1.rebnconvin.conv_s1.bias", "gt_encoder.stage1.rebnconvin.bn_s1.weight", "gt_encoder.stage1.rebnconvin.bn_s1.bias", "gt_encoder.stage1.rebnconvin.bn_s1.running_mean", "gt_encoder.stage1.rebnconvin.bn_s1.running_var", "gt_encoder.stage1.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv1.conv_s1.weight", "gt_encoder.stage1.rebnconv1.conv_s1.bias", "gt_encoder.stage1.rebnconv1.bn_s1.weight", "gt_encoder.stage1.rebnconv1.bn_s1.bias", "gt_encoder.stage1.rebnconv1.bn_s1.running_mean", "gt_encoder.stage1.rebnconv1.bn_s1.running_var", "gt_encoder.stage1.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv2.conv_s1.weight", "gt_encoder.stage1.rebnconv2.conv_s1.bias", "gt_encoder.stage1.rebnconv2.bn_s1.weight", "gt_encoder.stage1.rebnconv2.bn_s1.bias", "gt_encoder.stage1.rebnconv2.bn_s1.running_mean", "gt_encoder.stage1.rebnconv2.bn_s1.running_var", "gt_encoder.stage1.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv3.conv_s1.weight", "gt_encoder.stage1.rebnconv3.conv_s1.bias", "gt_encoder.stage1.rebnconv3.bn_s1.weight", "gt_encoder.stage1.rebnconv3.bn_s1.bias", "gt_encoder.stage1.rebnconv3.bn_s1.running_mean", "gt_encoder.stage1.rebnconv3.bn_s1.running_var", "gt_encoder.stage1.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv4.conv_s1.weight", "gt_encoder.stage1.rebnconv4.conv_s1.bias", "gt_encoder.stage1.rebnconv4.bn_s1.weight", "gt_encoder.stage1.rebnconv4.bn_s1.bias", "gt_encoder.stage1.rebnconv4.bn_s1.running_mean", "gt_encoder.stage1.rebnconv4.bn_s1.running_var", "gt_encoder.stage1.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv5.conv_s1.weight", "gt_encoder.stage1.rebnconv5.conv_s1.bias", "gt_encoder.stage1.rebnconv5.bn_s1.weight", "gt_encoder.stage1.rebnconv5.bn_s1.bias", "gt_encoder.stage1.rebnconv5.bn_s1.running_mean", "gt_encoder.stage1.rebnconv5.bn_s1.running_var", "gt_encoder.stage1.rebnconv5.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv6.conv_s1.weight", "gt_encoder.stage1.rebnconv6.conv_s1.bias", "gt_encoder.stage1.rebnconv6.bn_s1.weight", "gt_encoder.stage1.rebnconv6.bn_s1.bias", "gt_encoder.stage1.rebnconv6.bn_s1.running_mean", "gt_encoder.stage1.rebnconv6.bn_s1.running_var", "gt_encoder.stage1.rebnconv6.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv7.conv_s1.weight", "gt_encoder.stage1.rebnconv7.conv_s1.bias", "gt_encoder.stage1.rebnconv7.bn_s1.weight", "gt_encoder.stage1.rebnconv7.bn_s1.bias", "gt_encoder.stage1.rebnconv7.bn_s1.running_mean", "gt_encoder.stage1.rebnconv7.bn_s1.running_var", "gt_encoder.stage1.rebnconv7.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv6d.conv_s1.weight", "gt_encoder.stage1.rebnconv6d.conv_s1.bias", "gt_encoder.stage1.rebnconv6d.bn_s1.weight", "gt_encoder.stage1.rebnconv6d.bn_s1.bias", "gt_encoder.stage1.rebnconv6d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv6d.bn_s1.running_var", "gt_encoder.stage1.rebnconv6d.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv5d.conv_s1.weight", "gt_encoder.stage1.rebnconv5d.conv_s1.bias", "gt_encoder.stage1.rebnconv5d.bn_s1.weight", "gt_encoder.stage1.rebnconv5d.bn_s1.bias", "gt_encoder.stage1.rebnconv5d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv5d.bn_s1.running_var", "gt_encoder.stage1.rebnconv5d.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv4d.conv_s1.weight", "gt_encoder.stage1.rebnconv4d.conv_s1.bias", "gt_encoder.stage1.rebnconv4d.bn_s1.weight", "gt_encoder.stage1.rebnconv4d.bn_s1.bias", "gt_encoder.stage1.rebnconv4d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv4d.bn_s1.running_var", "gt_encoder.stage1.rebnconv4d.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv3d.conv_s1.weight", "gt_encoder.stage1.rebnconv3d.conv_s1.bias", "gt_encoder.stage1.rebnconv3d.bn_s1.weight", "gt_encoder.stage1.rebnconv3d.bn_s1.bias", "gt_encoder.stage1.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv3d.bn_s1.running_var", "gt_encoder.stage1.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv2d.conv_s1.weight", "gt_encoder.stage1.rebnconv2d.conv_s1.bias", "gt_encoder.stage1.rebnconv2d.bn_s1.weight", "gt_encoder.stage1.rebnconv2d.bn_s1.bias", "gt_encoder.stage1.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv2d.bn_s1.running_var", "gt_encoder.stage1.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage1.rebnconv1d.conv_s1.weight", "gt_encoder.stage1.rebnconv1d.conv_s1.bias", "gt_encoder.stage1.rebnconv1d.bn_s1.weight", "gt_encoder.stage1.rebnconv1d.bn_s1.bias", "gt_encoder.stage1.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage1.rebnconv1d.bn_s1.running_var", "gt_encoder.stage1.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconvin.conv_s1.weight", "gt_encoder.stage2.rebnconvin.conv_s1.bias", "gt_encoder.stage2.rebnconvin.bn_s1.weight", "gt_encoder.stage2.rebnconvin.bn_s1.bias", "gt_encoder.stage2.rebnconvin.bn_s1.running_mean", "gt_encoder.stage2.rebnconvin.bn_s1.running_var", "gt_encoder.stage2.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv1.conv_s1.weight", "gt_encoder.stage2.rebnconv1.conv_s1.bias", "gt_encoder.stage2.rebnconv1.bn_s1.weight", "gt_encoder.stage2.rebnconv1.bn_s1.bias", "gt_encoder.stage2.rebnconv1.bn_s1.running_mean", "gt_encoder.stage2.rebnconv1.bn_s1.running_var", "gt_encoder.stage2.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv2.conv_s1.weight", "gt_encoder.stage2.rebnconv2.conv_s1.bias", "gt_encoder.stage2.rebnconv2.bn_s1.weight", "gt_encoder.stage2.rebnconv2.bn_s1.bias", "gt_encoder.stage2.rebnconv2.bn_s1.running_mean", "gt_encoder.stage2.rebnconv2.bn_s1.running_var", "gt_encoder.stage2.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv3.conv_s1.weight", "gt_encoder.stage2.rebnconv3.conv_s1.bias", "gt_encoder.stage2.rebnconv3.bn_s1.weight", "gt_encoder.stage2.rebnconv3.bn_s1.bias", "gt_encoder.stage2.rebnconv3.bn_s1.running_mean", "gt_encoder.stage2.rebnconv3.bn_s1.running_var", "gt_encoder.stage2.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv4.conv_s1.weight", "gt_encoder.stage2.rebnconv4.conv_s1.bias", "gt_encoder.stage2.rebnconv4.bn_s1.weight", "gt_encoder.stage2.rebnconv4.bn_s1.bias", "gt_encoder.stage2.rebnconv4.bn_s1.running_mean", "gt_encoder.stage2.rebnconv4.bn_s1.running_var", "gt_encoder.stage2.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv5.conv_s1.weight", "gt_encoder.stage2.rebnconv5.conv_s1.bias", "gt_encoder.stage2.rebnconv5.bn_s1.weight", "gt_encoder.stage2.rebnconv5.bn_s1.bias", "gt_encoder.stage2.rebnconv5.bn_s1.running_mean", "gt_encoder.stage2.rebnconv5.bn_s1.running_var", "gt_encoder.stage2.rebnconv5.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv6.conv_s1.weight", "gt_encoder.stage2.rebnconv6.conv_s1.bias", "gt_encoder.stage2.rebnconv6.bn_s1.weight", "gt_encoder.stage2.rebnconv6.bn_s1.bias", "gt_encoder.stage2.rebnconv6.bn_s1.running_mean", "gt_encoder.stage2.rebnconv6.bn_s1.running_var", "gt_encoder.stage2.rebnconv6.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv5d.conv_s1.weight", "gt_encoder.stage2.rebnconv5d.conv_s1.bias", "gt_encoder.stage2.rebnconv5d.bn_s1.weight", "gt_encoder.stage2.rebnconv5d.bn_s1.bias", "gt_encoder.stage2.rebnconv5d.bn_s1.running_mean", "gt_encoder.stage2.rebnconv5d.bn_s1.running_var", "gt_encoder.stage2.rebnconv5d.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv4d.conv_s1.weight", "gt_encoder.stage2.rebnconv4d.conv_s1.bias", "gt_encoder.stage2.rebnconv4d.bn_s1.weight", "gt_encoder.stage2.rebnconv4d.bn_s1.bias", "gt_encoder.stage2.rebnconv4d.bn_s1.running_mean", "gt_encoder.stage2.rebnconv4d.bn_s1.running_var", "gt_encoder.stage2.rebnconv4d.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv3d.conv_s1.weight", "gt_encoder.stage2.rebnconv3d.conv_s1.bias", "gt_encoder.stage2.rebnconv3d.bn_s1.weight", "gt_encoder.stage2.rebnconv3d.bn_s1.bias", "gt_encoder.stage2.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage2.rebnconv3d.bn_s1.running_var", "gt_encoder.stage2.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv2d.conv_s1.weight", "gt_encoder.stage2.rebnconv2d.conv_s1.bias", "gt_encoder.stage2.rebnconv2d.bn_s1.weight", "gt_encoder.stage2.rebnconv2d.bn_s1.bias", "gt_encoder.stage2.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage2.rebnconv2d.bn_s1.running_var", "gt_encoder.stage2.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage2.rebnconv1d.conv_s1.weight", "gt_encoder.stage2.rebnconv1d.conv_s1.bias", "gt_encoder.stage2.rebnconv1d.bn_s1.weight", "gt_encoder.stage2.rebnconv1d.bn_s1.bias", "gt_encoder.stage2.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage2.rebnconv1d.bn_s1.running_var", "gt_encoder.stage2.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconvin.conv_s1.weight", "gt_encoder.stage3.rebnconvin.conv_s1.bias", "gt_encoder.stage3.rebnconvin.bn_s1.weight", "gt_encoder.stage3.rebnconvin.bn_s1.bias", "gt_encoder.stage3.rebnconvin.bn_s1.running_mean", "gt_encoder.stage3.rebnconvin.bn_s1.running_var", "gt_encoder.stage3.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv1.conv_s1.weight", "gt_encoder.stage3.rebnconv1.conv_s1.bias", "gt_encoder.stage3.rebnconv1.bn_s1.weight", "gt_encoder.stage3.rebnconv1.bn_s1.bias", "gt_encoder.stage3.rebnconv1.bn_s1.running_mean", "gt_encoder.stage3.rebnconv1.bn_s1.running_var", "gt_encoder.stage3.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv2.conv_s1.weight", "gt_encoder.stage3.rebnconv2.conv_s1.bias", "gt_encoder.stage3.rebnconv2.bn_s1.weight", "gt_encoder.stage3.rebnconv2.bn_s1.bias", "gt_encoder.stage3.rebnconv2.bn_s1.running_mean", "gt_encoder.stage3.rebnconv2.bn_s1.running_var", "gt_encoder.stage3.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv3.conv_s1.weight", "gt_encoder.stage3.rebnconv3.conv_s1.bias", "gt_encoder.stage3.rebnconv3.bn_s1.weight", "gt_encoder.stage3.rebnconv3.bn_s1.bias", "gt_encoder.stage3.rebnconv3.bn_s1.running_mean", "gt_encoder.stage3.rebnconv3.bn_s1.running_var", "gt_encoder.stage3.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv4.conv_s1.weight", "gt_encoder.stage3.rebnconv4.conv_s1.bias", "gt_encoder.stage3.rebnconv4.bn_s1.weight", "gt_encoder.stage3.rebnconv4.bn_s1.bias", "gt_encoder.stage3.rebnconv4.bn_s1.running_mean", "gt_encoder.stage3.rebnconv4.bn_s1.running_var", "gt_encoder.stage3.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv5.conv_s1.weight", "gt_encoder.stage3.rebnconv5.conv_s1.bias", "gt_encoder.stage3.rebnconv5.bn_s1.weight", "gt_encoder.stage3.rebnconv5.bn_s1.bias", "gt_encoder.stage3.rebnconv5.bn_s1.running_mean", "gt_encoder.stage3.rebnconv5.bn_s1.running_var", "gt_encoder.stage3.rebnconv5.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv4d.conv_s1.weight", "gt_encoder.stage3.rebnconv4d.conv_s1.bias", "gt_encoder.stage3.rebnconv4d.bn_s1.weight", "gt_encoder.stage3.rebnconv4d.bn_s1.bias", "gt_encoder.stage3.rebnconv4d.bn_s1.running_mean", "gt_encoder.stage3.rebnconv4d.bn_s1.running_var", "gt_encoder.stage3.rebnconv4d.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv3d.conv_s1.weight", "gt_encoder.stage3.rebnconv3d.conv_s1.bias", "gt_encoder.stage3.rebnconv3d.bn_s1.weight", "gt_encoder.stage3.rebnconv3d.bn_s1.bias", "gt_encoder.stage3.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage3.rebnconv3d.bn_s1.running_var", "gt_encoder.stage3.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv2d.conv_s1.weight", "gt_encoder.stage3.rebnconv2d.conv_s1.bias", "gt_encoder.stage3.rebnconv2d.bn_s1.weight", "gt_encoder.stage3.rebnconv2d.bn_s1.bias", "gt_encoder.stage3.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage3.rebnconv2d.bn_s1.running_var", "gt_encoder.stage3.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage3.rebnconv1d.conv_s1.weight", "gt_encoder.stage3.rebnconv1d.conv_s1.bias", "gt_encoder.stage3.rebnconv1d.bn_s1.weight", "gt_encoder.stage3.rebnconv1d.bn_s1.bias", "gt_encoder.stage3.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage3.rebnconv1d.bn_s1.running_var", "gt_encoder.stage3.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconvin.conv_s1.weight", "gt_encoder.stage4.rebnconvin.conv_s1.bias", "gt_encoder.stage4.rebnconvin.bn_s1.weight", "gt_encoder.stage4.rebnconvin.bn_s1.bias", "gt_encoder.stage4.rebnconvin.bn_s1.running_mean", "gt_encoder.stage4.rebnconvin.bn_s1.running_var", "gt_encoder.stage4.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv1.conv_s1.weight", "gt_encoder.stage4.rebnconv1.conv_s1.bias", "gt_encoder.stage4.rebnconv1.bn_s1.weight", "gt_encoder.stage4.rebnconv1.bn_s1.bias", "gt_encoder.stage4.rebnconv1.bn_s1.running_mean", "gt_encoder.stage4.rebnconv1.bn_s1.running_var", "gt_encoder.stage4.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv2.conv_s1.weight", "gt_encoder.stage4.rebnconv2.conv_s1.bias", "gt_encoder.stage4.rebnconv2.bn_s1.weight", "gt_encoder.stage4.rebnconv2.bn_s1.bias", "gt_encoder.stage4.rebnconv2.bn_s1.running_mean", "gt_encoder.stage4.rebnconv2.bn_s1.running_var", "gt_encoder.stage4.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv3.conv_s1.weight", "gt_encoder.stage4.rebnconv3.conv_s1.bias", "gt_encoder.stage4.rebnconv3.bn_s1.weight", "gt_encoder.stage4.rebnconv3.bn_s1.bias", "gt_encoder.stage4.rebnconv3.bn_s1.running_mean", "gt_encoder.stage4.rebnconv3.bn_s1.running_var", "gt_encoder.stage4.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv4.conv_s1.weight", "gt_encoder.stage4.rebnconv4.conv_s1.bias", "gt_encoder.stage4.rebnconv4.bn_s1.weight", "gt_encoder.stage4.rebnconv4.bn_s1.bias", "gt_encoder.stage4.rebnconv4.bn_s1.running_mean", "gt_encoder.stage4.rebnconv4.bn_s1.running_var", "gt_encoder.stage4.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv3d.conv_s1.weight", "gt_encoder.stage4.rebnconv3d.conv_s1.bias", "gt_encoder.stage4.rebnconv3d.bn_s1.weight", "gt_encoder.stage4.rebnconv3d.bn_s1.bias", "gt_encoder.stage4.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage4.rebnconv3d.bn_s1.running_var", "gt_encoder.stage4.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv2d.conv_s1.weight", "gt_encoder.stage4.rebnconv2d.conv_s1.bias", "gt_encoder.stage4.rebnconv2d.bn_s1.weight", "gt_encoder.stage4.rebnconv2d.bn_s1.bias", "gt_encoder.stage4.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage4.rebnconv2d.bn_s1.running_var", "gt_encoder.stage4.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage4.rebnconv1d.conv_s1.weight", "gt_encoder.stage4.rebnconv1d.conv_s1.bias", "gt_encoder.stage4.rebnconv1d.bn_s1.weight", "gt_encoder.stage4.rebnconv1d.bn_s1.bias", "gt_encoder.stage4.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage4.rebnconv1d.bn_s1.running_var", "gt_encoder.stage4.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconvin.conv_s1.weight", "gt_encoder.stage5.rebnconvin.conv_s1.bias", "gt_encoder.stage5.rebnconvin.bn_s1.weight", "gt_encoder.stage5.rebnconvin.bn_s1.bias", "gt_encoder.stage5.rebnconvin.bn_s1.running_mean", "gt_encoder.stage5.rebnconvin.bn_s1.running_var", "gt_encoder.stage5.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv1.conv_s1.weight", "gt_encoder.stage5.rebnconv1.conv_s1.bias", "gt_encoder.stage5.rebnconv1.bn_s1.weight", "gt_encoder.stage5.rebnconv1.bn_s1.bias", "gt_encoder.stage5.rebnconv1.bn_s1.running_mean", "gt_encoder.stage5.rebnconv1.bn_s1.running_var", "gt_encoder.stage5.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv2.conv_s1.weight", "gt_encoder.stage5.rebnconv2.conv_s1.bias", "gt_encoder.stage5.rebnconv2.bn_s1.weight", "gt_encoder.stage5.rebnconv2.bn_s1.bias", "gt_encoder.stage5.rebnconv2.bn_s1.running_mean", "gt_encoder.stage5.rebnconv2.bn_s1.running_var", "gt_encoder.stage5.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv3.conv_s1.weight", "gt_encoder.stage5.rebnconv3.conv_s1.bias", "gt_encoder.stage5.rebnconv3.bn_s1.weight", "gt_encoder.stage5.rebnconv3.bn_s1.bias", "gt_encoder.stage5.rebnconv3.bn_s1.running_mean", "gt_encoder.stage5.rebnconv3.bn_s1.running_var", "gt_encoder.stage5.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv4.conv_s1.weight", "gt_encoder.stage5.rebnconv4.conv_s1.bias", "gt_encoder.stage5.rebnconv4.bn_s1.weight", "gt_encoder.stage5.rebnconv4.bn_s1.bias", "gt_encoder.stage5.rebnconv4.bn_s1.running_mean", "gt_encoder.stage5.rebnconv4.bn_s1.running_var", "gt_encoder.stage5.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv3d.conv_s1.weight", "gt_encoder.stage5.rebnconv3d.conv_s1.bias", "gt_encoder.stage5.rebnconv3d.bn_s1.weight", "gt_encoder.stage5.rebnconv3d.bn_s1.bias", "gt_encoder.stage5.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage5.rebnconv3d.bn_s1.running_var", "gt_encoder.stage5.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv2d.conv_s1.weight", "gt_encoder.stage5.rebnconv2d.conv_s1.bias", "gt_encoder.stage5.rebnconv2d.bn_s1.weight", "gt_encoder.stage5.rebnconv2d.bn_s1.bias", "gt_encoder.stage5.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage5.rebnconv2d.bn_s1.running_var", "gt_encoder.stage5.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage5.rebnconv1d.conv_s1.weight", "gt_encoder.stage5.rebnconv1d.conv_s1.bias", "gt_encoder.stage5.rebnconv1d.bn_s1.weight", "gt_encoder.stage5.rebnconv1d.bn_s1.bias", "gt_encoder.stage5.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage5.rebnconv1d.bn_s1.running_var", "gt_encoder.stage5.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconvin.conv_s1.weight", "gt_encoder.stage6.rebnconvin.conv_s1.bias", "gt_encoder.stage6.rebnconvin.bn_s1.weight", "gt_encoder.stage6.rebnconvin.bn_s1.bias", "gt_encoder.stage6.rebnconvin.bn_s1.running_mean", "gt_encoder.stage6.rebnconvin.bn_s1.running_var", "gt_encoder.stage6.rebnconvin.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv1.conv_s1.weight", "gt_encoder.stage6.rebnconv1.conv_s1.bias", "gt_encoder.stage6.rebnconv1.bn_s1.weight", "gt_encoder.stage6.rebnconv1.bn_s1.bias", "gt_encoder.stage6.rebnconv1.bn_s1.running_mean", "gt_encoder.stage6.rebnconv1.bn_s1.running_var", "gt_encoder.stage6.rebnconv1.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv2.conv_s1.weight", "gt_encoder.stage6.rebnconv2.conv_s1.bias", "gt_encoder.stage6.rebnconv2.bn_s1.weight", "gt_encoder.stage6.rebnconv2.bn_s1.bias", "gt_encoder.stage6.rebnconv2.bn_s1.running_mean", "gt_encoder.stage6.rebnconv2.bn_s1.running_var", "gt_encoder.stage6.rebnconv2.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv3.conv_s1.weight", "gt_encoder.stage6.rebnconv3.conv_s1.bias", "gt_encoder.stage6.rebnconv3.bn_s1.weight", "gt_encoder.stage6.rebnconv3.bn_s1.bias", "gt_encoder.stage6.rebnconv3.bn_s1.running_mean", "gt_encoder.stage6.rebnconv3.bn_s1.running_var", "gt_encoder.stage6.rebnconv3.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv4.conv_s1.weight", "gt_encoder.stage6.rebnconv4.conv_s1.bias", "gt_encoder.stage6.rebnconv4.bn_s1.weight", "gt_encoder.stage6.rebnconv4.bn_s1.bias", "gt_encoder.stage6.rebnconv4.bn_s1.running_mean", "gt_encoder.stage6.rebnconv4.bn_s1.running_var", "gt_encoder.stage6.rebnconv4.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv3d.conv_s1.weight", "gt_encoder.stage6.rebnconv3d.conv_s1.bias", "gt_encoder.stage6.rebnconv3d.bn_s1.weight", "gt_encoder.stage6.rebnconv3d.bn_s1.bias", "gt_encoder.stage6.rebnconv3d.bn_s1.running_mean", "gt_encoder.stage6.rebnconv3d.bn_s1.running_var", "gt_encoder.stage6.rebnconv3d.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv2d.conv_s1.weight", "gt_encoder.stage6.rebnconv2d.conv_s1.bias", "gt_encoder.stage6.rebnconv2d.bn_s1.weight", "gt_encoder.stage6.rebnconv2d.bn_s1.bias", "gt_encoder.stage6.rebnconv2d.bn_s1.running_mean", "gt_encoder.stage6.rebnconv2d.bn_s1.running_var", "gt_encoder.stage6.rebnconv2d.bn_s1.num_batches_tracked", "gt_encoder.stage6.rebnconv1d.conv_s1.weight", "gt_encoder.stage6.rebnconv1d.conv_s1.bias", "gt_encoder.stage6.rebnconv1d.bn_s1.weight", "gt_encoder.stage6.rebnconv1d.bn_s1.bias", "gt_encoder.stage6.rebnconv1d.bn_s1.running_mean", "gt_encoder.stage6.rebnconv1d.bn_s1.running_var", "gt_encoder.stage6.rebnconv1d.bn_s1.num_batches_tracked", "gt_encoder.side1.weight", "gt_encoder.side1.bias", "gt_encoder.side2.weight", "gt_encoder.side2.bias", "gt_encoder.side3.weight", "gt_encoder.side3.bias", "gt_encoder.side4.weight", "gt_encoder.side4.bias", "gt_encoder.side5.weight", "gt_encoder.side5.bias", "gt_encoder.side6.weight", "gt_encoder.side6.bias".
 ```

**Comment by pythongosssss** [comment]
I think the only pre-trained ckpt in the anime-seg repo is for `isnetis`, so make sure to choose net of `isnet_is`

**Comment by marcussacana** [comment]
It worked, thank you!
