### ISSUE TITLE
Cannot read properties of undefined (reading '0') at ComfyWidgets.COMBO

### ISSUE THREAD

**Issue by filipemeneses** [pythongosssss/ComfyUI-Custom-Scripts#118]
Updated ComfyUI recently and started to get this error, I'm using this [workflow](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/13325452/workflow.3.json)

```
TypeError: Cannot read properties of undefined (reading '0')
    at ComfyWidgets.COMBO (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/betterCombos.js:135:26)
    at nodeType.checkPrimitiveWidget (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:160:50)
    at nodeType.onGraphConfigured (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:136:11)
    at app.graph.onConfigure (http://127.0.0.1:8188/scripts/app.js:1230:29)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1217:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1516:15)
    at reader.onload (http://127.0.0.1:8188/scripts/app.js:1853:11)
```

**Comment by filipemeneses** [comment]
Loading the workflow from an image instead of a JSON works fine, apparently
