### ISSUE TITLE
Sound not being triggered (WinError 10054)

### ISSUE THREAD

**Issue by acgc99** [pythongosssss/ComfyUI-Custom-Scripts#310]
I often get this error with PlaySound node:
```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```
This happens to me in console and also in Stability Matrix. Unfortunately, it seems to happen randomly, I haven't observed any patern.

**Comment by pythongosssss** [comment]
Hmm, they playsound node doesnt have any logic on the backend so I would be suprised if it was this node causing the issue
