### ISSUE TITLE
better_combos: encoded url and substring not found

### ISSUE THREAD

**Issue by universorum** [pythongosssss/ComfyUI-Custom-Scripts#332]
Whan add the `Lora Loader` node, the console will hint `substring not found` error.

Browser: Firefox 130.0b9 on Windows

```
Traceback (most recent call last):
  File ".miniforge3/envs/comfy/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".miniforge3/envs/comfy/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".miniforge3/envs/comfy/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "comfy/server.py", line 61, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/comfy/server.py", line 73, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "comfy/custom_nodes/ComfyUI-Custom-Scripts/py/better_combos.py", line 58, in get_examples
    pos = name.index("/")
          ^^^^^^^^^^^^^^^
ValueError: substring not found
```

The problem is the variable `name` is encoded uri that mean the `/` will be encoded to `%2F`. We should call `urllib.parse.unquote` before find the index of `/`.

**Comment by zebbsb** [comment]
yes，it works. Adding 'name = parse.unquote(name)' after 'name = request.match_info["name"]'

**Comment by Moxie1776** [comment]
> yes，it works. Adding 'name = parse.unquote(name)' after 'name = request.match_info["name"]'

I opened this up in vscode, implemented this fix in multiple places, and it did fix all the issues I'm having. Thanks :)

**Comment by LinuxWhiz** [comment]
Harley as And  huh

**Comment by Lalimec** [comment]
Is this caused by a comfy update or sth?

**Comment by Jatts-Art** [comment]
> For those coming across this issue, this solution worked for me as well, I'll try to explain the solution in a bit more detail for those who aren't as well versed in modifying python code (like me).
> 
> Go to this folder _...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py_ There are two files that needs to be modified; "**better_combos.py**" and "**model_info.py**" Open these files with your preferred text editor like, notepad.
> 
> At the top of each file there will be text like this:
> 
> ```
> import glob
> import os
> from nodes import LoraLoader, CheckpointLoaderSimple
> import folder_paths
> from server import PromptServer
> from folder_paths import get_directory_by_type
> from aiohttp import web
> import shutil
> ```
> 
> At the end add this text: `from urllib.parse import unquote`
> 
> it should look like this:
> 
> ```
> from folder_paths import get_directory_by_type
> from aiohttp import web
> import shutil
> from urllib.parse import unquote
> ```
> 
> Then in each document look for all places where you can find these lines (_you can use your text editors search function or just have a look yourself_):
> 
> ```
>     name = request.match_info["name"]
>     pos = name.index("/")
> ```
> 
> In between these lines add: `name = unquote(name)` It should now look like this:
> 
> ```
>     name = request.match_info["name"]
>     name = unquote(name)
>     pos = name.index("/")
> ```
> 
> There is 4 places this text needs to be added in "**better_combos.py**", and 2 places in "**model_info.py**".
> 
> Save each file when your done and next time you boot up ComfyUI this issue should hopefully be resolved.

Doing this does indeed fix the issue... however, be aware, that this _changes the model's file format if you do so._ I followed the steps exactly, and it results in model file formats all being changes to ".sha256" for whatever reason, which then causes it to break when trying to use.

EDIT: Oh actually its worse, it destroyed the file itself and reduced them down to 64 bytes lmfao. Yeah this is no fix at all.

**Comment by aa-parky** [comment]
Just confirming this worked for me too. Thank you.
