### ISSUE TITLE
Bug: SaveText UnicodeEncodeError

### ISSUE THREAD

**Issue by EnragedAntelope** [pythongosssss/ComfyUI-Custom-Scripts#380]
Hi,
When I have a nonstandard character within the text that I am trying to save, I receive an error. Can this be addressed?

In this case it was "Zdzisław Beksiński" if you need an example. Below is the error I received. Thank you!

```
2024-10-28 13:58:53,847 - root - ERROR - !!! Exception during processing !!! 'charmap' codec can't encode character '\u0142' in position 205: character maps to <undefined>
2024-10-28 13:58:53,863 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\text_files.py", line 187, in write_text
    f.write(kwargs["text"])
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 205: character maps to <undefined>

```

**Comment by Epicurusismyhomeboy** [comment]
@EnragedAntelope Did you ever resolve this issue?

I had a similar encoding error issue that popped up recently which I had thought was due to my Windows regional settings not being in UTF-8, so I switched that, but then I started consistently getting decode errors when attempting the same task. ComfyUI's error handler points to SaveText|pysssss but I can't find any other issue in this repository referencing UTF-8 errors. 

```!!! Exception during processing !!! 'utf-8' codec can't decode byte 0x92 in position 6710: invalid start byte
Traceback (most recent call last):
  File "G:\CU\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\CU\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\CU\custom_nodes\comfyui-lora-manager\py\metadata_collector\metadata_hook.py", line 165, in async_map_node_over_list_with_metadata
    results = await original_map_node_over_list(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\CU\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "G:\CU\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "G:\CU\custom_nodes\comfyui-custom-scripts\py\text_files.py", line 193, in write_text
    return super().load_text(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\CU\custom_nodes\comfyui-custom-scripts\py\text_files.py", line 95, in load_text
    return (f.read(), )
            ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 6710: invalid start byte```
