### ISSUE TITLE
A few small issues with viewing lora info

### ISSUE THREAD

**Issue by Davikar** [pythongosssss/ComfyUI-Custom-Scripts#45]
First, it doesn't seem like it can load the metadata from all types of models. This is fairly rare, but it affects a few models and I don't know what's different about them. They can be read in A1111 (well, SD Next to be exact, but should be the same).
I get the following error message in the console when hitting the View Info button:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\AI\ComfyUI\ComfyUI\server.py", line 43, in cache_control
    response: web.Response = await handler(request)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\lora_info.py", line 52, in load_metadata
    meta["pysssss.sha256"] = hashlib.sha256(f.read()).hexdigest()
TypeError: 'NoneType' object does not support item assignment
```

Also, when there's no metadata at all I get the following error message in the Comfy log:

```
TypeError
Cannot destructure property 'buckets' of 'JSON.parse(...)' as it is null.
TypeError: Cannot destructure property 'buckets' of 'JSON.parse(...)' as it is null.
    at get resolutions [as resolutions] (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/loraInfo.js:54:12)
    at new LoraInfoDialog (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/loraInfo.js:143:10)
    at HTMLDivElement.callback (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/loraInfo.js:304:7)

```

**Comment by pythongosssss** [comment]
These two crashes should now both be fixed

**Comment by Davikar** [comment]
Working perfectly now. 👍

**Comment by Davikar** [comment]
Working perfectly now. 👍
