### ISSUE TITLE
The problem with this extension. 

### ISSUE THREAD

**Issue by mikheys** [pythongosssss/ComfyUI-Custom-Scripts#47]
Today this extension stopped working on installed Comfyui. I installed a clean Comfy, installed the manager and this extension, when loading I get a window with an error.

------------------------------------------------

Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'apply')
TypeError: Cannot read properties of undefined (reading 'apply')
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:38:27)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:38:27)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:38:27)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:38:27)
    at LGraph.add (http://127.0.0.1:8188/lib/litegraph.core.js:1465:18)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2232:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1230:15)
    at HTMLButtonElement.onclick (http://127.0.0.1:8188/scripts/ui.js:755:11)
This may be due to the following script:
/extensions/pysssss/CustomScripts/snapToGrid.js

**Comment by pythongosssss** [comment]
I wasn't able to recreate the issue, but hopefully that should now be fixed
