### ISSUE TITLE
"glob() got an unexpected keyword argument 'root_dir'"

### ISSUE THREAD

**Issue by RONNYKHALIL** [pythongosssss/ComfyUI-Custom-Scripts#49]
HI, I love these tools, but for some reason can't get them to load when using Paperspace. Used the Comfy Manager to install, and when running ComfyUI I get:

```
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts/__init__.py", line 12, in <module>
    files = glob.glob("*.py", root_dir=py, recursive=False)
TypeError: glob() got an unexpected keyword argument 'root_dir'

Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts module for custom nodes: glob() got an unexpected keyword argument 'root_dir'

Import times for custom nodes:
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds (IMPORT FAILED): /notebooks/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/SeargeSDXL
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Manager
   0.6 seconds: /notebooks/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   1.2 seconds: /notebooks/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
```

Previously I would get this error but still have access to the a few options like your image feed. Now it seems like none of your scripts show up. Any idea how to get around this 'root_dir' issue on paperspace?

thanks!

**Comment by pythongosssss** [comment]
Are you able to upgrade the version of python on Paperspace to 3.10? That's the recommended version for ComfyUI.
If it's not possible I can take a look at supporting an older version of Python
